name: amber_hackathon
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0

  cupertino_icons: ^1.0.8
  gsheets: ^0.5.0
  shared_preferences: ^2.2.2
  firebase_core: ^4.5.0
  cloud_firestore: ^6.1.3
  firebase_auth: ^6.2.0
  intl: ^0.19.0
  http: ^1.6.0
  image_picker: ^1.2.1
  flutter_dotenv: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

  flutter_lints: ^6.0.0

flutter:

  assets:
    - assets/logo.png



  uses-material-design: true
